name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    env: 
      DB_URL: postgresql://postgres:postgres@localhost:5432/postgres

    # TODO: run DB for testing somewhere else, because it takes too much time for the service to start
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Prepare Prisma
        run: npx prisma generate && npx prisma db push

      - name: Run tests
        run: npm run test
