name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    env: 
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: db
      DB_HOST: localhost
      DB_PORT: 5432
      DB_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${DB_NAME}
        ports:
          - ${DB_PORT}:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run tests
        run: npm run test
