name: Run Tests

on: push

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test
